[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
# color console
anstream = "0.6.15"
owo-colors = "4.1.0"

aes-gcm = "0.10"
base64 = "0.22.1"
fs2 = "0.4.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
